### ISSUE TITLE
`Tab` key (for Copilot completion) is conflicting in different situations.

### ISSUE THREAD

**Issue by jfcherng** [TerminalFi/LSP-copilot#10]
# Situation 1

There is no ST completion and there is only white spaces or nothing before the caret in the current line.

![image](https://user-images.githubusercontent.com/6594915/179339573-31485153-4799-4f6b-8d97-632604307c73.png)

If you press `Tab`, then ST inserts a tab.

# Situation 2

There is ST completion and Copilot completion.

![image](https://user-images.githubusercontent.com/6594915/179339614-fe0fee02-2a6e-46b4-a445-331a99bf5c05.png)

If you press `Tab`, then ST applies ST completion.

# Situation 3

If you are not in situation 1 or 2, then ST applies Copilot completion.

# Solution

The only solution I can figure out at this moment is using a more dedicated keybinding other than `Tab` to explicitly indicate "I want to apply Copilot completion". Like the following keybinding, for example, 

```js
    {
        "keys": ["ctrl+tab"], // Tab is the most abused keybinding when it comes to completion
        "command": "copilot_accept_suggestion",
        "context": [{ "key": "setting.copilot.completion.is_visible" }],
    },
```

Not sure how this is resolved in VSCode or other editors.

**Comment by TheSecEng** [comment]
In VSCode I believe copilot takes precedence over autocompletion. Which I don't think would be desired here.

**Comment by timfjord** [comment]
In VSCode copilot suggestions render inline, and they always take precedence. It is part of the core API and I don't think this can be even configured.

In neovim it is kind of the same https://github.com/github/copilot.vim/blob/release/doc/copilot.txt#L76-L78 but it didn't really work for me, probably because there were some overrides in my config.

I personally had to explicitly define the Copilot key binding in Sublime, because I had some existing overrides
```
{ "keys": ["tab"], "command": "next_field", "context": [
    { "key": "has_next_field", "operator": "equal", "operand": true }
  ]
},
{ "keys": ["tab"], "command": "commit_completion", "context": [
    { "key": "has_next_field", "operand": false },
    { "key": "auto_complete_visible" },
  ]
},
{ "keys": ["tab"], "command": "copilot_accept_suggestion", "context": [
    { "key": "copilot_suggestion_visible", "operator": "equal", "operand": true }
  ]
},
```

Theoretically, we could leave everything as it is but add a comment/README note that it might be required to explicitly define the key binding based on preferations.
Alternatively, we could define an extra key binding, but I would try to stick to defaults(`Tab` and `alt` + `[`/`]` for cycling)

**Comment by TheSecEng** [comment]
I think a key pattern is for LSP helpers to not override default Sublime keybindings. 

Perhaps have keybindings disabled by default ? Not sure honestly. Will default to both of yours decision.

**Comment by jfcherng** [comment]
Supposedly also resolved by https://github.com/TerminalFi/LSP-copilot/pull/140
