### ISSUE TITLE
`copilot.is_on_completion` context is not working

### ISSUE THREAD

**Issue by davidhcefx** [TerminalFi/LSP-copilot#146]
In [Default.sublime-keymap](https://github.com/TerminalFi/LSP-copilot/blob/master/Default.sublime-keymap), the command `copilot_accept_completion` cannot work, unless I commented out the following context:
```
            {
                "key": "copilot.is_on_completion"
            }
```
which indicates that this condition cannot be true when the completion dialog popped up.

**Comment by jfcherng** [comment]
`setting.copilot.completion.is_visible` seems to be the correct key. Not sure why we use `copilot.is_on_completion` at this moment. Maybe it's due to code refacoring.

**Comment by jfcherng** [comment]
It comes from https://github.com/TerminalFi/LSP-copilot/commit/b5b5806b2025837a74fc318ada285ef16385f84c. It has been like 1.5 years but you are the first one who complains. Weird.

**Comment by timfjord** [comment]
Yeah, I've been using this since the introduction and haven't had any issues (just in case, I use it with the `phantom` style completion).
Just one thing to mention, since this is the default behaviour, the competition won't be accepted unless the cursor is like directly on the completion (as described in #60), otherwise, it will fallback to the default behaviour.
@davidhcefx could you please record a video of the problem and upload it here as it might help to debug the issue

**Comment by davidhcefx** [comment]
@timfjord Oh, I must have missed out the part that the cursor has to be right at the point of the completed text. What I was trying is to bind `copilot_accept_completion` to another key different that `Tab`. But since the cursor is at the line beginning and there are a few tabs away from the completion, I cannot get anything upon pressing that key.
